name: CI

on: [push]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Prepare reports directory
        run: |
          mkdir -p lint-reports
          cp lib/build/reports/lint-results-debug.html lint-reports/lib-lint.html
          cp gui/build/reports/lint-results-debug.html lint-reports/gui-lint.html

      - name: Upload html reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-html-reports
          path: lint-reports/


