name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Prepare reports directory
        run: |
          mkdir -p lint-reports
          find . -type f -path "*/build/reports/lint-results-debug.html" | while read file; do
            module_name=$(echo "$file" | cut -d'/' -f2)
            cp "$file" "lint-reports/${module_name}-lint.html"
          done

      - name: Upload html reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-html-reports
          path: lint-reports/


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: ./gradlew test

      - name: Prepare reports directory
        run: |
            mkdir -p unit-tests-reports
            find . -type f -path "*/build/reports/tests/testDebugUnitTest/index.html" | while read file; do
              module_name=$(echo "$file" | cut -d'/' -f2)
              cp "$file" "unit-tests-reports/${module_name}-unit-tests.html"
            done

      - name: Upload html reports
        uses: actions/upload-artifact@v4

        with:
          name: unit-tests-html-reports
          path: unit-tests-reports/

  build_sample:
    if: github.ref == 'refs/heads/master'
    needs: [unit-test]
    name: "Assemble Android Debug Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false
          cache-read-only: false
          cache-write-only: false

      - name: Build Android Debug App
        run: ./gradlew :sample:assembleDebug --stacktrace


