name: Release Library

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Проверяем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Создаём новую версию на основе последнего тега
      - name: Bump Version and Create Tag
        id: bump_version
        run: |
          # Получаем последний тег
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          # Увеличиваем версию (мажор.минор.патч)
          VERSION=$(echo "$LATEST_TAG" | awk -F. '{print $1"."$2"."$3+1}')
          echo "New version: $VERSION"

          # Создаём новый тег
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      # Проверяем, что версия корректно обновлена в build.gradle.kts
      - name: Validate Version in Gradle
        run: |
          # Обновляем версию в build.gradle.kts
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" build.gradle.kts
          git add build.gradle.kts
          git commit -m "Update version to $VERSION"
          git push origin master
